# Generated by Django 4.2.7 on 2024-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('health_info_filled', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('height_feet', models.IntegerField()),
                ('height_inch', models.IntegerField()),
                ('weight', models.FloatField()),
                ('dob', models.DateField()),
                ('activity_level', models.CharField(max_length=50)),
                ('dietery_preference', models.CharField(max_length=100)),
                ('dietery_goal', models.CharField(max_length=100)),
                ('allergies', models.JSONField(default=list)),
                ('health_conditions', models.JSONField(default=list)),
            ],
        ),
    ]
