# Generated by Django 4.2.7 on 2024-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_activity_level_alter_user_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
