# Generated by Django 4.2.7 on 2024-11-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activity_level',
            new_name='ActivityLevel',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='height_feet',
            new_name='HeightFeet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='height_inch',
            new_name='HeightInch',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='weight',
            new_name='Weight',
        ),
    ]
