# Generated by Django 4.2.7 on 2024-11-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_activity_level_user_activitylevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
