# Generated by Django 4.2.7 on 2024-11-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ingredients', models.JSONField(help_text='List of ingredients with effects on health')),
                ('allergies', models.JSONField(blank=True, help_text='Allergies associated with this product', null=True)),
                ('benefits', models.JSONField(blank=True, help_text='Health benefits of this product', null=True)),
                ('flipkart_link', models.URLField(blank=True, max_length=500, null=True)),
                ('amazon_link', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='FoodProducts.category')),
            ],
        ),
    ]
